# Define the name of the GitHub Actions workflow
name: Python Image Build

# This workflow is triggered manually using workflow_dispatch
on:
  workflow_dispatch:
    # Define inputs for the manual trigger
    inputs:
      # Input for specifying the environment (like dev, staging, prod)
      environment:
        description: 'Environment to run the workflow against (e.g., dev, staging, prod)'
        required: true
        type: string
    
# Define the jobs to run
jobs:
  login-to-docker-hub:
      name: Login to Docker Hub
      # Log in to Docker Hub using the credentials from environment variables
      permissions:
          id-token: write # need this for OIDC
          contents: read
      uses: suddes/github-workflows-templates/blob/main/.github/workflows/docket_login.yml@main
      with:
            env: ${{ inputs.environment || 'dev' }}
      secrets: inherit
