# Define the name of the GitHub Actions workflow
name: Python Image Build

# This workflow is triggered manually using workflow_dispatch
on:
  workflow_dispatch:
    # Define inputs for the manual trigger
    inputs:
      # Input for specifying the environment (like dev, staging, prod)
      environment:
        description: 'Environment to run the workflow against (e.g., dev, staging, prod)'
        required: true
        type: string
    
# Define the jobs to run
jobs:
  call-local-workflow:
    uses: ./.github/workflows/local-workflow.yml
    secrets: inherit
